server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: "%msg%n"