global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'spring-boot-app'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

